version: '2'

services:
  scanner:
    build: ./scanner
    user: root
    restart: always
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server

  nginx:
      image: nginx:stable
      restart: always
      build: ./nginx
      ports:
        - 80:80
      depends_on:
        - scanner